name: Access ID Workflow

on:
  push:
    branches:
      - main  # Change this to your desired branch if not `main`

jobs:
  access-id-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Retrieve ACCESS_ID
        run: |
          echo "Access ID: $ACCESS_ID "
        env:
          ACCESS_ID: scaler-123
